//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ezGussetPlate.rc
//
#define IDC_EDIT_LINEAR_MEMBER_SHAPE    3
#define IDC_NEW_LINEAR_MEMBER           3
#define IDCANCEL2                       4
#define IDC_DELETE_LINEAR_MEMBER        4
#define IDD_ABOUTBOX                    99
#define IDP_OLE_INIT_FAILED             99
#define ID_VIEW_INFO                    100
#define ID_VIEW_ROTATE                  101
#define ID_VIEW_FIT                     102
#define ID_VIEW_ZOOM                    103
#define ID_OCC_VIEW_TOP                 104
#define ID_OCC_VIEW_LEFT                105
#define ID_OCC_VIEW_ISO                 106
#define IDS_RIBBON_OCC_VIEW             107
#define IDS_APP_GENERATE                108
#define IDS_APP_EXPORT                  109
#define IDB_WRITESMALL                  110
#define IDS_APP_OPTIONS                 110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define ID_OCC_VIEW_BOTTOM              112
#define IDB_BUTTONS                     113
#define ID_OCC_VIEW_RIGHT               113
#define IDB_FILELARGE                   114
#define ID_OCC_VIEW_FRONT               114
#define IDB_FILESMALL                   115
#define ID_OCC_VIEW_BACK                115
#define IDS_EXPORT_BREP                 116
#define IDS_EXPORT_IGES                 117
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_STATUS_PANE3                124
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SmartSteelTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_PLATE_CONFIG                310
#define IDB_BITMAP1                     311
#define IDB_BITMAP_CAMERA               311
#define IDD_LINEAR_MEMBER_SHAPE         312
#define IDD_EDIT_LINEAR_MEMBER_SHAPE    313
#define IDD_PROPERTY_SHEET              314
#define IDD_GUSSET_PLATE_SHAPE          315
#define IDD_GUSSET_PLATE_SHAPE1         316
#define IDD_END_PLATE_SHAPE             316
#define IDI_OK                          316
#define IDI_ICON1                       317
#define IDI_CANCEL                      317
#define IDD_LOGIN                       318
#define IDI_ICON2                       319
#define IDI_RESET_ACTIVATE_CODE         320
#define IDB_BITMAP2                     323
#define IDB_DEMO                        323
#define IDB_BITMAP3                     326
#define IDB_MESSAGES                    326
#define IDS_OCC_VIEW_SHADED             327
#define IDS_OCC_VIEW_WIREFRAME          328
#define IDB_BITMAP4                     329
#define IDD_WORK_STATUS                 330
#define ID_ROTATE_ABOUT_AXIS            331
#define IDC_EDIT_CLASS                  1000
#define IDC_EDIT_GRADE                  1001
#define IDC_COMBO1                      1002
#define IDC_COMBO_GUSSET_PLATE_COLOR    1002
#define IDC_COMBO_END_PLATE_COLOR       1003
#define IDC_CHECK_GENERATE_FOR_WEB_TYPE_BRACE 1004
#define IDC_STATIC_NEW_MEMBER           1005
#define IDC_CHECK_GENERATE_ENDPLATE     1005
#define IDC_STATIC_EXISTING_MEMBER      1006
#define IDC_STATIC_LINEAR_MEMBER_SHAPE  1007
#define IDC_EDIT_MAX_EDGE_LENGTH        1007
#define IDC_EDIT_SECTION_NAME           1008
#define IDC_TREE_PAGE                   1009
#define IDC_STATIC_PAGE                 1010
#define IDC_COMBO_PROJECT               1011
#define IDC_COMBO2                      1011
#define IDC_COMBO_UNIT                  1011
#define IDC_EDIT1                       1012
#define IDC_BUTTON_RESET_ACTIVATE_CODE  1013
#define IDC_BUTTON1                     1014
#define IDC_STATIC_MSG                  1015
#define IDC_PROGRESS1                   1016
#define IDC_PROGRESS                    1016
#define IDC_EDIT_ID                     1017
#define IDC_STATIC_IMAGE                1017
#define IDC_STATIC_PLATE_IMAGE          1017
#define IDC_EDIT_PASSWORD               1018
#define IDC_STATIC_TITLE                1059
#define IDC_STATIC_PROJECT              1071
#define IDC_STATIC_ID                   1072
#define IDC_STATIC_PASSWORD             1073
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_DELETE                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
